function savepdffigure(handle,path)

tmp = get(handle,'Position');
set(handle,...
    'DefaultAxesFontSize',5,...
    'DefaultLineLineWidth',2,...
    'PaperUnits','points',...
    'PaperSize',[tmp(3) tmp(4)],... was [11.5 8]
    'PaperPosition',[0 0 tmp(3) tmp(4)]); %was [0 0 11.5 8]
saveas(handle,path,'pdf');
